### ISSUE TITLE
Error when plugin enables before world is loaded

### ISSUE THREAD

**Issue by diamond-gold** [utarwyn/SuperJukebox#20]
When the plugin enables, the world has not been loaded by Multiverse yet
Error when loading jukebox1
fr.utarwyn.superjukebox.jukebox.config.JukeboxConfigurationException: bad location
	at fr.utarwyn.superjukebox.jukebox.JukeboxesManager.createJukebox(JukeboxesManager.java:182) ~[?:?]
	at fr.utarwyn.superjukebox.jukebox.JukeboxesManager.lambda$initialize$0(JukeboxesManager.java:44) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at fr.utarwyn.superjukebox.jukebox.JukeboxesManager.initialize(JukeboxesManager.java:52) ~[?:?]
	at fr.utarwyn.superjukebox.AbstractManager.<init>(AbstractManager.java:51) ~[?:?]
	at fr.utarwyn.superjukebox.jukebox.JukeboxesManager.<init>(JukeboxesManager.java:34) ~[?:?]
	at fr.utarwyn.superjukebox.SuperJukebox.onEnable(SuperJukebox.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-384]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-384]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-384]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by utarwyn** [comment]
Indeed the plugin does not wait custom worlds loading when there are jukeboxes in them. I have to work on that. Thank you for the feedback!

**Comment by utarwyn** [comment]
Hello, the latest development build should fix that bug: https://ci.utarwyn.fr/job/SuperJukebox/8/
Sorry for the inconvenience, I have also planned to rewrite the jukebox management system because its a mess for now.
